name: Send MM Notify

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  alarm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Install dependencies
        uses: BSFishy/pip-action@v1
        with:
          packages: requests
      - name: Run script
        run: python3 static/mm_notify.py
        env:
          MM_HOST: ${{ secrets.MM_HOST }}
          SC_KEY: ${{ secrets.SC_KEY }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          MM_COOKIE: ${{ secrets.MM_COOKIE }}
          ALERT_FROM: ${{ secrets.ALERT_FROM }}
          ALERT_TO: ${{ secrets.ALERT_TO }}
